apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-dev
  name: simple-deployment
spec:
  selector:
    matchLabels:
      app: webapp-dev
  template:
    metadata:
      labels:
        app: webapp-dev
